"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/sharedComponents/Navbar'
import LeftSidebar from '@/components/sharedComponents/LeftSideBar'
import { MyProvider } from '@/context/MyContext'
import Link from 'next/link';
import {FiLink2} from 'react-icons/fi'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Button } from '@/components/ui/button'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyProvider>
      <main className="flex flex-row  font-roboto ">
      <section className="navbarOverviewContainer grow flex flex-col">
        <div className='websiteNavbar'>
        <nav className="navbar p-4 flex justify-between w-full items-center ">
      <div className="flex items-center gap-[47px] text-[16px] font-[400]">
        {/* <Link href="/overview">
          Overview
        </Link> */}
        <Link className='flex flex-col items-center justify-center' href="/mailbox">
          <div>
            Home
          </div>
          <svg width="63" height="8" viewBox="0 0 63 8" fill="none" xmlns="http://www.w3.org/2000/svg">
           <path d="M0 8C0 3.58172 3.58172 0 8 0H55C59.4183 0 63 3.58172 63 8H0Z" fill="#69A959"/>
          </svg>
        </Link>
        {/* <Link href="/jobs/all">
          Jobs
        </Link> */}
      </div>
      <form className=' flex justify-center items-center  '>
        

          <div className='relative'>
          <div className='absolute left-[12px] top-[8px]'>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M11 20C15.9706 20 20 15.9706 20 11C20 6.02944 15.9706 2 11 2C6.02944 2 2 6.02944 2 11C2 15.9706 6.02944 20 11 20Z" stroke="#989898" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M18.9299 20.6898C19.4599 22.2898 20.6699 22.4498 21.5999 21.0498C22.4499 19.7698 21.8899 18.7198 20.3499 18.7198C19.2099 18.7098 18.5699 19.5998 18.9299 20.6898Z" stroke="#989898" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </div>
          <input
            type="text"
            placeholder="I am looking for..."
            className="navbarSearchInput rounded-[4px] p-2 w-[400px] h-[40px] block pl-12 font-[500] text-[14px]"
          />
        </div>
      </form>
      
      <div className="flex items-center gap-[47px] text-[16px] font-[400]">
        <Link href="/overview">
         About Us
        </Link>
        <Link className='flex flex-col items-center justify-center' href="/mailbox">
          <div>
            Jobs
          </div>
          <svg width="63" height="8" viewBox="0 0 63 8" fill="none" xmlns="http://www.w3.org/2000/svg">
           <path d="M0 8C0 3.58172 3.58172 0 8 0H55C59.4183 0 63 3.58172 63 8H0Z" fill="#69A959"/>
          </svg>
        </Link>
        <Link href="/jobs/all">
          Contact Us
        </Link>

        <Button type='button'>Login</Button>
        <Button type='button'>Sign Up</Button>
      </div>
    </nav>
        </div>
        <div className="p-2 w-full">
          {/* <Overview/> */}{children}
        </div>
      </section>
    </main>
    </MyProvider>
        {/* {children} */}
        
      </body>
    </html>
  )
}
