"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/sharedComponents/Navbar'
import LeftSidebar from '@/components/sharedComponents/LeftSideBar'
// import { MyProvider } from '@/context/MyContext'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-row  font-roboto ">
      <div className="grow">
      <LeftSidebar/>
      </div>
      <div className="navbarOverviewContainer grow flex flex-col">
          {children}
      </div>
    </div>
        
      </body>
    </html>
        </ClerkProvider>
  )
}
